version: 3
includes:
  blot: services/go-services/blot/Taskfile.yml
  grpc-api: schemas/grpc/Taskfile.yml
  deployment: deployment/native/mac/Taskfile.yml

vars:
  BLOT_SERVICE_ADDRESS: '{{.BLOT_SERVICE_ADDRESS | default "127.0.0.1:8080"}}'

tasks:
  install-grpcui:
    desc: Install grpcui
    cmds:
      - go install github.com/fullstorydev/grpcui/cmd/grpcui@latest

  install-envoy:
    desc: Install envoy
    cmds:
      - brew install envoy

  install-dependencies:
    desc: Install dependencies
    cmds:
      - cd services/go-services && go mod download
      - cd services/go-services && task install-golangci-lint

  test:
    desc: Run all tests
    cmds:
      - cd services/go-services && task test

  lint:
    desc: Run linter
    cmds:
      - cd services/go-services && task lint