version: '3'

tasks:
  smoke-test-get-gameset:
    desc: Smoke test get game
    vars:
      BLOT_SERVICE_ADDRESS: '{{.BLOT_SERVICE_ADDRESS | default "127.0.0.1:8081"}}'
    cmds:
      - |
        grpcurl -vv -plaintext -d '{
          "id": "71199AC4-DDA2-47F1-A207-2EF9E5C48498",
          "player_id": "b88bb98e-0e1f-4c82-a209-9d6b4986d013"
        }' {{.BLOT_SERVICE_ADDRESS}} blotservice.v1beta1.BlotService.GetGameSetForPlayer

  smoke-test-create-gameset:
    desc: Smoke test create game
    vars:
      BLOT_SERVICE_ADDRESS: '{{.BLOT_SERVICE_ADDRESS | default "127.0.0.1:8081"}}'
    cmds:
        - |
            grpcurl -vv -plaintext -d '{
                "id": "71199AC4-DDA2-47F1-A207-2EF9E5C48498",
                "first_player": "Lilit"
            }' {{.BLOT_SERVICE_ADDRESS}} blotservice.v1beta1.BlotService.CreateGameSet

  smoke-test-create-wrong-gameset:
    desc: Smoke test create game
    vars:
      BLOT_SERVICE_ADDRESS: '{{.BLOT_SERVICE_ADDRESS | default "127.0.0.1:8081"}}'
    cmds:
        - |
            grpcurl -vv -plaintext -d '{
                "id": "71199AC4-DDA2-47F1-A207-2EF9E5C48498",
                "first_player": ""
            }' {{.BLOT_SERVICE_ADDRESS}} blotservice.v1beta1.BlotService.CreateGameSet

