service:
  flush: 1
  log_level: info
  parsers_file: parsers.conf

pipeline:
  inputs:
    #    - name: tail
    #      tag: file
    #      path: /var/logs/*.log
    #      parser: json
    #      refresh_interval: 10
    - name: tail
      tag: file.<app>
      tag_regex: (?<app>[^/]+)\.log$
      path: /var/logs/*.log
      parser: json
      key: log # see https://docs.fluentbit.io/manual/pipeline/inputs/tail
      refresh_interval: 10 # the interval of refreshing the list of watched files in seconds.
      path_key: _metadata_file_path
      processors:
        logs:
          - name: content_modifier
            action: extract
            key: "_metadata_file_path"
            pattern: (?<app>[^/]+)\.log$

  #    - name: tail
  #      tag: docker.<container_id>
  #      tag_regex: (?<container_id>[^/]+)-json\.log$
  #      path: /var/lib/docker/containers/*/*-json.log
  #      parser: docker
  #      refresh_interval: 10

  outputs:
    - name: loki
      match: "*"
      host: loki
      port: 3100
      labels: job=logs, app=$app, level=$level, command=$command, query=$query
      retry_limit: 20
      storage.total_limit_size: 1000M
