apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    isDefault: true
    version: 1
    editable: false
  - name: Tempo
    type: tempo
    uid: EbPG8fYo1
    url: http://tempo:3200
    access: proxy
    basicAuth: false
    jsonData:
      nodeGraph:
        enabled: true
      search:
        hide: false
      traceQuery:
        timeShiftEnabled: true
        spanStartTimeShift: '1h'
        spanEndTimeShift: '-1h'
      tracesToLogsV2:
        datasourceUid: 'Loki'
        spanStartTimeShift: '-1h'
        spanEndTimeShift: '1h'
        filterByTraceID: false
        filterBySpanID: false
        customQuery: true
        query: '{app="$${__span.tags["service.name"]}"} | json | trace_id="$${__span.traceId}" | span_id="$${__span.spanId}" | line_format `{{.message}}`'
